In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler 
from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
from sklearn.linear_model import RidgeCV

In [3]:
# Task-
# X 2D and Y prep
# X train and X test prediction
# Correlation
# Standard Scaler
# LinearModel
# Ridge 
# Lasso
# coeff, aplha, pipeline use dekh lena
# Then Score r2 root means, yeh sab

In [5]:
df = pd.read_csv("Credit.csv")

In [8]:
df.dtypes

ID             int64
Income       float64
Limit          int64
Rating         int64
Cards          int64
Age            int64
Education      int64
Gender        object
Student       object
Married       object
Ethnicity     object
Balance        int64
dtype: object

In [9]:
df.head()

,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
2,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
3,4,148.924,9504,681,3,36,11,Female,No,No,Asian,964
4,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331


In [10]:
numerical_columns = df.select_dtypes(include = ['number'])

In [11]:
numerical_columns.columns

Index(['ID', 'Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education',
       'Balance'],
      dtype='object')

In [12]:
numerical_columns.drop(columns=['ID'],inplace=True)

In [13]:
numerical_columns.columns

Index(['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education', 'Balance'], dtype='object')

In [14]:
# Correlation between all
#  Pandas way 
corr = numerical_columns.corr()
corr

,Income,Limit,Rating,Cards,Age,Education,Balance
Income,1.000000,0.792088,0.791378,-0.018273,0.175338,-0.027692,0.463656
Limit,0.792088,1.000000,0.996880,0.010231,0.100888,-0.023549,0.861697
Rating,0.791378,0.996880,1.000000,0.053239,0.103165,-0.030136,0.863625
Cards,-0.018273,0.010231,0.053239,1.000000,0.042948,-0.051084,0.086456
Age,0.175338,0.100888,0.103165,0.042948,1.000000,0.003619,0.001835
Education,-0.027692,-0.023549,-0.030136,-0.051084,0.003619,1.000000,-0.008062
Balance,0.463656,0.861697,0.863625,0.086456,0.001835,-0.008062,1.000000


In [15]:
X = numerical_columns.to_numpy()

In [18]:
corr = np.corrcoef(X.T)
# All X features ek line mein chahta hamesha
corr

array([[ 1.        ,  0.79208834,  0.79137763, -0.01827261,  0.1753384 ,
        -0.02769198,  0.46365646],
       [ 0.79208834,  1.        ,  0.99687974,  0.01023133,  0.10088792,
        -0.02354853,  0.86169727],
       [ 0.79137763,  0.99687974,  1.        ,  0.05323903,  0.103165  ,
        -0.03013563,  0.86362516],
       [-0.01827261,  0.01023133,  0.05323903,  1.        ,  0.04294829,
        -0.05108422,  0.08645635],
       [ 0.1753384 ,  0.10088792,  0.103165  ,  0.04294829,  1.        ,
         0.00361928,  0.00183512],
       [-0.02769198, -0.02354853, -0.03013563, -0.05108422,  0.00361928,
         1.        , -0.00806158],
       [ 0.46365646,  0.86169727,  0.86362516,  0.08645635,  0.00183512,
        -0.00806158,  1.        ]])

In [19]:
X = numerical_columns.drop(columns = ['Limit'])
y= numerical_columns['Limit']

In [20]:
X.shape

(400, 6)

In [21]:
y.shape

(400,)

In [25]:
scaler = StandardScaler()

In [26]:
X_scaled = scaler.fit(X)

In [30]:
X_scaled.scale_
# Each column ka separate scale and mean
X_scaled.mean_

array([ 45.218885, 354.94    ,   2.9575  ,  55.6675  ,  13.45    ,
       520.015   ])

In [32]:
X_scaled = scaler.transform(X)

In [38]:
np.isnan(X_scaled).sum()

np.int64(0)

In [42]:
type(y)

numpy.ndarray

In [43]:
y = y.to_numpy()

AttributeError: 'numpy.ndarray' object has no attribute 'to_numpy'

In [44]:
y

array([ 3606,  6645,  7075,  9504,  4897,  8047,  3388,  7114,  3300,
        6819,  8117,  1311,  5308,  6922,  3291,  2525,  3714,  4378,
        6384,  6626,  2860,  6378,  2631,  5179,  1757,  4323,  3625,
        4534, 13414,  5611,  5666,  2733,  7838,  1829,  2646,  2558,
        6457,  6481,  3899,  3461,  3327,  7659,  4763,  6257,  6375,
        7569,  5043,  4431,  2252,  4569,  5183,  3969,  5441,  5466,
        1499,  1786,  4742,  4779,  3480,  5294,  5198,  3089,  1671,
        2998,  2937,  4160,  9704,  5099,  5619,  6819,  3954,  7402,
        4923,  4523,  5390,  3180,  3293,  3254,  6662,  2101,  3449,
        4263,  4433,  1433,  2906, 12066,  6340,  2271,  4307,  7518,
        5767,  6040,  2832,  5435,  3075,   855,  5382,  3388,  2963,
        8494,  3736,  2433,  7582,  9540,  4768,  3182,  1337,  3189,
        6033,  3261,  3271,  2959,  6637,  6386,  3326,  4828,  2117,
        9113,  2161,  1410,  1402,  8157,  7056,  1300,  2529,  2531,
        5533,  3411,

In [45]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.4, random_state=0)

In [47]:
X_train.shape
X_test.shape

(160, 6)

In [49]:
# Linear Model OLS Based Parameters aayenge
linearReg= LinearRegression()
linearReg.fit(X_train,y_train)
y_test_pred= linearReg.predict(X_test)
print("Coef",linearReg.coef_)
print("intercept",linearReg.intercept_)
# After prediction accuracies
print("R2score",r2_score(y_test, y_test_pred))
print("RMSE",root_mean_squared_error(y_test, y_test_pred))

Coef [ 2.63606506e+01  2.23805339e+03 -1.04689841e+02  2.17731970e+00
  1.90514866e+01  5.31845320e+01]
intercept 4732.5680787279
R2score 0.9948561527526879
RMSE 156.94360473601034


In [50]:
# without scaled x using pipeline
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4, random_state=0)

In [62]:
# Pipeline to use Ridge and Lassso
ridge = Pipeline([('scaler', StandardScaler()), ('ridge', RidgeCV())])
ridge.fit(X_train,y_train)
y_test_pred= ridge.predict(X_test)
# print(dir(ridge))
my_ridge= ridge.named_steps["ridge"]
print("Coef",my_ridge.coef_)
print("intercept",my_ridge.intercept_)
print("alpharidge",my_ridge.alpha_)
my_scaler = ridge.named_steps["scaler"]
print("scales",my_scaler.scale_ )
# After prediction accuracies
print("R2score",r2_score(y_test, y_test_pred))
print("RMSE",root_mean_squared_error(y_test, y_test_pred))

Coef [  36.1056659  2287.61725447 -104.41515761    2.48330134   18.78569731
   64.93731984]
intercept 4718.4
alpharidge 0.1
scales [ 36.17899497 159.18464771   1.36940148  17.48942091   3.12266579
 464.79242363]
R2score 0.9948608369916638
RMSE 156.87212819717698
