In [4]:
# # Task
# # X,y train test split
# # numerical and caterogical
# # imputer median most frequent scaler numberical - onehotencode categorical
# # pipelines
# # column transform for varierty of columns

# # Models:
# # Logistic Regression with and without penalty

# # KNN
# # NB
# # Decision Tree
# Fit and Predict

# confusion matrix 
# Scores
# accuracy precision recall and f1

SyntaxError: invalid syntax (327276278.py, line 16)

In [7]:
import numpy as np
import pandas as pd, numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, precision_score, recall_score, f1_score, accuracy_score
import matplotlib.pyplot as plt

In [16]:
df = pd.read_csv("titanic.csv")

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [14]:
# df['Sex']= df['Sex'].map({'male':0,'female':1})

In [18]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [19]:
numerical_df = df.select_dtypes(include= ['number'])
categorical_df = df.select_dtypes(include= ['object'])

In [23]:
numerical_df['Parch'].unique()
# column toh hua

array([0, 1, 2, 5, 3, 4, 6])

In [24]:
numerical_df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [27]:
categorical_df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [25]:
categorical_df.columns

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [20]:
numerical_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [93]:
y= df['Survived']

In [94]:
num_col = ['Age',"Fare"]
cat_col = ["SibSp","Parch","Cabin","Embarked","Sex","Pclass"]

In [95]:
numerical_df = df[num_col]
categorical_df = df[cat_col]
num_col = numerical_df.columns.to_list()
cat_col = categorical_df.columns.to_list()
X = df[cat_col+num_col]

In [96]:
X.shape
y.shape

(891,)

In [76]:
# If imputer and standard scaler individually for numerical df
num_imputer = SimpleImputer(strategy='mean')
num_imputer.fit(numerical_df)
i = num_imputer.transform(numerical_df)
i

array([[22.        ,  7.25      ],
       [38.        , 71.2833    ],
       [26.        ,  7.925     ],
       ...,
       [29.69911765, 23.45      ],
       [26.        , 30.        ],
       [32.        ,  7.75      ]], shape=(891, 2))

In [77]:
scaler = StandardScaler()
scaler.fit(i)
i_num = scaler.transform(i)
i_num

array([[-0.5924806 , -0.50244517],
       [ 0.63878901,  0.78684529],
       [-0.2846632 , -0.48885426],
       ...,
       [ 0.        , -0.17626324],
       [-0.2846632 , -0.04438104],
       [ 0.17706291, -0.49237783]], shape=(891, 2))

In [63]:
# If imputer and one hot individually for categorical df
cat_imputer = SimpleImputer(strategy='most_frequent')
cat_imputer.fit(categorical_df)
i = cat_imputer.transform(categorical_df)
i

array([[1, 0, 'B96 B98', 'S', 'male', 3],
       [1, 0, 'C85', 'C', 'female', 1],
       [0, 0, 'B96 B98', 'S', 'female', 3],
       ...,
       [1, 2, 'B96 B98', 'S', 'female', 3],
       [0, 0, 'C148', 'C', 'male', 1],
       [0, 0, 'B96 B98', 'Q', 'male', 3]], shape=(891, 6), dtype=object)

In [64]:
onehotencoder = OneHotEncoder(handle_unknown='ignore')
onehotencoder.fit(categorical_df)
i_cat = onehotencoder.transform(categorical_df)
onehotencoder.get_feature_names_out(cat_col)
i_cat.shape

(891, 171)

In [ ]:
#  X_ new is basically i_num + i_cat

In [121]:
#  Now using pipelines life easier
numerical_pipeline = Pipeline([('num_imputer', SimpleImputer(strategy='median')), ('scaler', MinMaxScaler())])
categorical_pipeline = Pipeline([('cat_imputer', SimpleImputer(strategy='most_frequent')), ('onehotencoder', OneHotEncoder(handle_unknown='ignore'))])

In [79]:
# Fitting same thing 
i = numerical_pipeline.fit_transform(numerical_df)
numerical_pipeline.named_steps['scaler'].scale_

array([12.99471687, 49.66553444])

In [ ]:
i = categorical_pipeline.fit_transform(categorical_df)
categorical_pipeline.named_steps['onehotencoder'].get_feature_names_out(cat_col)

In [86]:
# All in one like creating final X and inside X num_col and cat_col separately process
column_transformer = ColumnTransformer(
    [("numerical", numerical_pipeline, num_col),
     ("categorical", categorical_pipeline, cat_col)])


In [87]:
# X = column_transformer.fit_transform(X)

In [92]:
column_transformer.named_transformers_['numerical'].named_steps['scaler'].scale_
# named_transformers_['numerical'] return pipeline or us flow pe jo value hai currently pipeline

array([12.99471687, 49.66553444])

In [119]:
# All the Algos and Score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [105]:
logistic_regression =Pipeline([('preprocess', column_transformer), ('algo', LogisticRegression())])
# LogisticRegression(penalty=penalty, C=C, solver=solver, max_iter=2000))
logistic_regression.fit(X_train,y_train)
y_pred = logistic_regression.predict(X_test) 
#  X_test while predicting missing values is fitted using X_train fit values in pipelines
# print("coeff",logistic_regression.named_steps['algo'].coef_ )
cm = confusion_matrix(y_test,y_pred)
print(cm)
# precision_score, recall_score, f1_score, accuracy_score
print("accuracy",accuracy_score(y_test,y_pred),"precision",precision_score(y_test,y_pred),"recall",recall_score(y_test,y_pred),"f1score",f1_score(y_test,y_pred))

[[95 15]
 [19 50]]
accuracy 0.8100558659217877 precision 0.7692307692307693 recall 0.7246376811594203 f1score 0.746268656716418


In [114]:
decision_tree =Pipeline([('preprocess', column_transformer), ('algo', DecisionTreeClassifier(max_depth=4))])
decision_tree.fit(X_train,y_train)
y_pred = decision_tree.predict(X_test) 
#  X_test while predicting missing values is fitted using X_train fit values in pipelines
cm = confusion_matrix(y_test,y_pred)
# print(decision_tree.named_steps["algo"].feature_importances_)
print(cm)
# precision_score, recall_score, f1_score, accuracy_score
print("accuracy",accuracy_score(y_test,y_pred),"precision",precision_score(y_test,y_pred),"recall",recall_score(y_test,y_pred),"f1score",f1_score(y_test,y_pred))

[[104   6]
 [ 31  38]]
accuracy 0.7932960893854749 precision 0.8636363636363636 recall 0.5507246376811594 f1score 0.672566371681416


In [ ]:
from sklearn.naive_bayes import MultinomialNB
nb =Pipeline([('preprocess', column_transformer), ('algo', MultinomialNB())])
nb.fit(X_train,y_train)
y_pred = nb.predict(X_test) 
#  X_test while predicting missing values is fitted using X_train fit values in pipelines
cm = confusion_matrix(y_test,y_pred)
print(cm)
# precision_score, recall_score, f1_score, accuracy_score
print("accuracy",accuracy_score(y_test,y_pred),"precision",precision_score(y_test,y_pred),"recall",recall_score(y_test,y_pred),"f1score",f1_score(y_test,y_pred))

In [124]:
knn = Pipeline([
    ("preprocess", column_transformer),
    ("model", KNeighborsClassifier(n_neighbors=5))
])
# Fit directly on X and y
knn.fit(X_train, y_train)

# Predict
y_pred = knn.predict(X_test)
cm = confusion_matrix(y_test,y_pred)
print(cm)
# precision_score, recall_score, f1_score, accuracy_score
print("accuracy",accuracy_score(y_test,y_pred),"precision",precision_score(y_test,y_pred),"recall",recall_score(y_test,y_pred),"f1score",f1_score(y_test,y_pred))

[[98 12]
 [23 46]]
accuracy 0.8044692737430168 precision 0.7931034482758621 recall 0.6666666666666666 f1score 0.7244094488188977
