## Lab:1 - My Summary

Load Data

In [2]:
import pandas as pd                               # For working with datasets (loading, cleaning, etc.)
import numpy as np

In [3]:
df = pd.read_csv("/content/airline_satisfaction_missing.csv")
df.head()

Unnamed: 0      id  Gender      Customer Type  Age   Type of Travel  \
0           0   70172    Male     Loyal Customer   13  Personal Travel   
1           1    5047    Male  disloyal Customer   25  Business travel   
2           2  110028  Female     Loyal Customer   26  Business travel   
3           3   24026  Female     Loyal Customer   25  Business travel   
4           4  119299    Male     Loyal Customer   61  Business travel   

      Class  Flight Distance  Inflight wifi service  \
0  Eco Plus              460                      3   
1  Business              235                      3   
2  Business             1142                      2   
3  Business              562                      2   
4  Business              214                      3   

   Departure/Arrival time convenient  ...  On-board service  Leg room service  \
0                                  4  ...                 4                 3   
1                                  2  ...                 1                 5   
2                                  2  ...                 4                 3   
3                                  5  ...                 2                 5   
4                                  3  ...                 3                 4   

   Baggage handling  Checkin service  Inflight service  Cleanliness  \
0                 4                4                 5            5   
1                 3                1                 4            1   
2                 4                4                 4            5   
3                 3                1                 4            2   
4                 4                3                 3            3   

   Departure Delay in Minutes  Arrival Delay in Minutes  \
0                          25                      18.0   
1                           1                       6.0   
2                           0                       0.0   
3                          11                       9.0   
4                           0                       0.0   

              satisfaction  target  
0  neutral or dissatisfied       0  
1  neutral or dissatisfied       0  
2                satisfied       1  
3  neutral or dissatisfied       0  
4                satisfied       1  

[5 rows x 26 columns]

In [5]:
df.shape

(103904, 26)

In [4]:
df.isnull().sum()

Unnamed: 0                              0
id                                      0
Gender                                  0
Customer Type                           0
Age                                     0
Type of Travel                          0
Class                                   0
Flight Distance                         0
Inflight wifi service                   0
Departure/Arrival time convenient       0
Ease of Online booking                  0
Gate location                           0
Food and drink                          0
Online boarding                         0
Seat comfort                         1039
Inflight entertainment                  0
On-board service                        0
Leg room service                        0
Baggage handling                        0
Checkin service                         0
Inflight service                        0
Cleanliness                             0
Departure Delay in Minutes              0
Arrival Delay in Minutes             1345
satisfaction                            0
target                                  0
dtype: int64

### EDA
- Get 2-3 factors impacting target

In [11]:
# Target count
x= df['target'].value_counts()
percentage = x/len(df)*100
print(percentage)
# The dataset is reasonably balanced, with a slightly higher proportion of not satisfied passengers.

target
0    56.666731
1    43.333269
Name: count, dtype: float64


In [12]:
df.shape

(103904, 26)

In [14]:
# dropping column
non_feature_columns = ["Unnamed: 0", "id", "satisfaction", "target"]
df_new = df.drop(non_feature_columns, axis=1)
df_new.head()
df_new.shape

(103904, 22)

In [15]:
# types of data and category split
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   Gender                             103904 non-null  object 
 1   Customer Type                      103904 non-null  object 
 2   Age                                103904 non-null  int64  
 3   Type of Travel                     103904 non-null  object 
 4   Class                              103904 non-null  object 
 5   Flight Distance                    103904 non-null  int64  
 6   Inflight wifi service              103904 non-null  int64  
 7   Departure/Arrival time convenient  103904 non-null  int64  
 8   Ease of Online booking             103904 non-null  int64  
 9   Gate location                      103904 non-null  int64  
 10  Food and drink                     103904 non-null  int64  
 11  Online boarding                    1039

In [29]:
df.dtypes.to_string()

'Unnamed: 0                             int64\nid                                     int64\nGender                                object\nCustomer Type                         object\nAge                                    int64\nType of Travel                        object\nClass                                 object\nFlight Distance                        int64\nInflight wifi service                  int64\nDeparture/Arrival time convenient      int64\nEase of Online booking                 int64\nGate location                          int64\nFood and drink                         int64\nOnline boarding                        int64\nSeat comfort                         float64\nInflight entertainment                 int64\nOn-board service                       int64\nLeg room service                       int64\nBaggage handling                       int64\nCheckin service                        int64\nInflight service                       int64\nCleanliness                      

In [34]:
categorical_columns = df_new.select_dtypes(include=['object']).columns.tolist()
print(categorical_columns,type(categorical_columns))
categorical_columns = df_new.select_dtypes(include=['object']).columns.tolist()
print(categorical_columns,type(categorical_columns))

numerical_columns = df_new.select_dtypes(include=['number']).columns.tolist()
print(numerical_columns,type(numerical_columns))

['Gender', 'Customer Type', 'Type of Travel', 'Class'] <class 'list'>
['Gender', 'Customer Type', 'Type of Travel', 'Class'] <class 'list'>
['Age', 'Flight Distance', 'Inflight wifi service', 'Departure/Arrival time convenient', 'Ease of Online booking', 'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort', 'Inflight entertainment', 'On-board service', 'Leg room service', 'Baggage handling', 'Checkin service', 'Inflight service', 'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes'] <class 'list'>


Missing Values Fixes
: Numerical columns : median se replace
: Categorical columns : mode se replace

In [ ]:
df_new.isna().sum()

Handling Missing Values:
- use imputers for columns
- df[column].fillna() method can be used too

In [40]:
df['Seat comfort'].isnull().sum()

np.int64(1039)

In [42]:
df['Gender'].mode()

'Female'

In [ ]:
# My style of handling missing values
for item in numerical_columns:
  print(item)
  df[item].fillna(df[item].median(), inplace=True)

for item in categorical_columns:
  print(item)
  df[item].fillna(df[item].mode()[0], inplace=True)

Using Imputers for missing values
- For each numeric column in num_data:

  Compute the median (since you set strategy="median").

  Store these medians inside the imputer object.

- But fit_transform() always returns a NumPy array, not a DataFrame.

  Shape = (n_samples, n_features)

  Column names are lost.

  Need to wrap in pd.Dataframe()

In [47]:
# Split the dataset into numeric and categorical subsets
num_data = df[numerical_columns]
cat_data = df[categorical_columns]
cat_data.head()
print(type(num_data))

<class 'pandas.core.frame.DataFrame'>


In [48]:
from sklearn.impute import SimpleImputer

In [51]:
num_imputer = SimpleImputer(strategy="median")
cat_imputer = SimpleImputer(strategy="most_frequent")

a = num_imputer.fit_transform(num_data)
# all missing values are handled
b = cat_imputer.fit_transform(cat_data)

print(a,type(a))

[[1.300e+01 4.600e+02 3.000e+00 ... 5.000e+00 2.500e+01 1.800e+01]
 [2.500e+01 2.350e+02 3.000e+00 ... 1.000e+00 1.000e+00 6.000e+00]
 [2.600e+01 1.142e+03 2.000e+00 ... 5.000e+00 0.000e+00 0.000e+00]
 ...
 [3.000e+01 1.995e+03 1.000e+00 ... 4.000e+00 7.000e+00 1.400e+01]
 [2.200e+01 1.000e+03 1.000e+00 ... 1.000e+00 0.000e+00 0.000e+00]
 [2.700e+01 1.723e+03 1.000e+00 ... 1.000e+00 0.000e+00 0.000e+00]] <class 'numpy.ndarray'>


Convert numpy to dataframe with name

In [ ]:
num_df = pd.DataFrame(a, columns=numerical_columns)
cat_df = pd.DataFrame(b, columns=categorical_columns)
cat_data.isna().sum()
# Maam one line num_imputed = pd.DataFrame(num_imputer.fit_transform(num_data), columns=numeric_features)

Can mix these columns together now

In [60]:
# Combine the imputed DataFrames
df_after_imputation = pd.concat([num_df,cat_df],axis=1)
# axis=1 → concatenate columns (stack data horizontally)
df_after_imputation.isnull().sum().sum()

np.int64(0)

Remaining Missing Values: 0
The dataset is now complete and ready for further analysis.